"""Convert an owner-labelled golden worksheet CSV into the golden-episodes-v1 fixture.

Each labelled worksheet row becomes one JSONL row consumed by
``tests_support.golden_episodes``: the episode window spans from the first
incident's ``detected_at`` minus ``--lead`` seconds to the last incident's
``detected_at`` plus the event-type horizon (fall 120 s, bed-exit 60 s), so a
replay alert anywhere inside the merged episode counts as that episode's one
alert. Rows without a label are rejected (exit 2), never silently skipped.
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path

HORIZON_SEC = {"fall": 120.0, "bed-exit": 60.0}
EVENT_TYPE = {"fall": "fall", "bed-exit": "bed_exit"}


def _ns(value: str) -> int:
    return int(datetime.fromisoformat(value).timestamp() * 1_000_000_000)


def convert(worksheet: Path, output: Path, lead_sec: float) -> int:
    with worksheet.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    lines: list[str] = []
    for index, row in enumerate(rows, start=1):
        label = (row.get("label") or "").strip()
        if not label:
            raise SystemExit(f"row {index} ({row.get('episode_id')}) has no label")
        event_type = row["event_type"]
        horizon = HORIZON_SEC[event_type]
        record = {
            "camera_id": row["camera_id"],
            "event_type": EVENT_TYPE[event_type],
            "start_ns": _ns(row["detected_at"]) - int(lead_sec * 1_000_000_000),
            "end_ns": _ns(row["last_detected_at"]) + int(horizon * 1_000_000_000),
            "label": label,
        }
        lines.append(json.dumps(record, separators=(",", ":")))
    output.write_text(
        "# golden-episodes-v1; generated by scripts/qa/golden_from_worksheet.py\n"
        + "".join(line + "\n" for line in lines),
        encoding="utf-8",
    )
    return len(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--worksheet", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--lead", type=float, default=5.0, help="seconds before detected_at")
    args = parser.parse_args()
    print(f"episodes={convert(args.worksheet, args.out, args.lead)} out={args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
